version: '2'

services:

  apache:
    build:
      context: ./env/apache
      dockerfile: Dockerfile-apache
    image: devops/apache
    ports:
    - 28088:80
    volumes:
    - ./:/var/www/html:rw
    restart: always
    links:
    - mysql

  mysql:
    image: mariadb:10.1
    ports:
    - 28033:3306
    env_file:
    - ./env/mysql/mysql.env
    volumes:
    - /var/lib/mysql