version: '2'

services:

  apache:
    build:
      context: ./env/apache
      dockerfile: Dockerfile-apache
    ports:
    - 28088:80
    volumes:
    - ./wp/:/var/www/html:rw
    - ./web/:/var/www/html/wp-content/themes/web:rw
    - ./src/:/var/www/html/wp-content/plugins/src:rw
    - ./logs/:/var/www/html/logs:rw
    restart: always
    links:
    - mysql

  mysql:
    image: mariadb:10.1
    ports:
    - 28033:3306
    env_file:
    - ./env/mysql/mysql.env
    volumes:
    - /var/lib/mysql